# Site settings
title: Simply Logical
subtitle: Intelligent Reasoning by Example
email: Peter.Flach@bristol.ac.uk
website: http://www.cs.bris.ac.uk/~flach/SimplyLogical.html
description: > # this means to ignore newlines until "baseurl:"
  This book discusses methods to implement intelligent reasoning by means of Prolog programs. 
  The book is written from the shared viewpoints of Computational Logic, which aims at automating 
  various kinds of reasoning, and Artificial Intelligence, which seeks to 
  implement aspects of intelligent behaviour on a computer. 
url: "https://book.simply-logical.space" # the base hostname & protocol for your site
baseurl: "" # the subpath of your site, e.g. /blog/
repo: "https://github.com/simply-logical/simply-logical"
swish: "https://swish.simply-logical.space/"
author: Peter Flach
# twitter_username: jekyllrb
# github_username:  jekyll

orgurl: "https://simply-logical.space"
google_analytics: "UA-112595762-2"

# Build settings
markdown: kramdown
